### PR TITLE
Do not supersample FTE particles

### PR DESCRIPTION
**Pull request by temx**

### CODE REVIEW

**Comment by Novum** [comment]
Any reasons for this?

**Comment by temx** [comment]
Performance, and performance variability.
* FTE particles can momentarily cause extreme overdraw (20x-100x)
* For both Nvidia and AMD multisampling large primitives is much faster than supersampling
* FTE particles don't benefit from supersampling (filtered, low frequency)

FTE particles use an atlas without mipmaps, so it's not necessary to undo the adjustment of the sampler LOD bias.

Some examples (note perf in lower right corner):
[Supersampled](https://user-images.githubusercontent.com/24851409/153715583-db4f5208-c39c-44b4-b6dd-019f10ae04b3.png) [Multisampled](https://user-images.githubusercontent.com/24851409/153715610-eefb2031-a421-4da4-a7c6-932bb8f3fa1d.png) [Off](https://user-images.githubusercontent.com/24851409/153715617-ac7f72c9-ba3b-4ff0-a5da-474e81e8c14a.png)
[Supersampled](https://user-images.githubusercontent.com/24851409/153715682-3c7c444b-6c48-4661-9f3e-7e0f04ffb28c.png) [Multisampled](https://user-images.githubusercontent.com/24851409/153715694-527f2d09-052f-4911-85ac-a8ea5bd9c1eb.png) [Off](https://user-images.githubusercontent.com/24851409/153715698-91eee6d9-a225-436a-b2a0-3c52d8e942d0.png)
[Supersampled](https://user-images.githubusercontent.com/24851409/153715706-ba51dd52-18aa-4ffc-961a-5b0ebfaacadf.png) [Multisampled](https://user-images.githubusercontent.com/24851409/153715719-9aa4ffe7-53e0-4912-b62f-a8cc291289ed.png) [Off](https://user-images.githubusercontent.com/24851409/153715722-ca34e459-3507-4d03-bda6-ce6a62c1496d.png)

**Comment by Novum** [comment]
I do understand the differences between multi- and supersampling, thank you very much.

The reason I wasn't considering this is that the fragment shader doesn't do much. I suspect the real reason this is causing a perf drop is that bandwidth compression isn't effective because of slight variability in the per-sample output colors

**Comment by temx** [comment]
For Nvidia at least, the bottleneck seems to be PROP:
image
If I'm not mistaken PROP drains fragments from the SMs but doesn't touch the framebuffer; the actual blending done in CROP, which seems unpressured. VRAM bandwidth is under 10%, I guess thanks to the automatic tiled rendering.

Switching to MSAA "balances" these units; CROP, RASTER and VRAM increase utilization.

**Comment by Novum** [comment]
Got it, bandwidth between SMs and ROPs then. Thanks for the fix, makes sense.

**Pull request merged**
