### PR TITLE
Restore r_scale option for resolution scaling

### LINKED ISSUE #229: Feature Request:  Resolution scaling.
Hi.  Would it be possible to implement the 'r_scale' function that was present in the original Quakespasm?  It's pretty enjoyable to replicate the classic quake look by pixelating the image.

https://github.com/Shpoike/Quakespasm/blob/master/quakespasm/Quake/gl_rmain.c#L1037

Thank you.

### PR DESCRIPTION
**Pull request by rg3**
This option can be used to simulate lower screen resolutions by giving it values greater than 1. The effect is implemented as a post-processing step and included as part of the screen warping underwater shaders.

Feel free to reject or request changes. I've gone the post-processing route as you mentioned in #229 it could be an easy solution.

Fixes #229.

### CODE REVIEW

**Comment by Novum** [comment]
Thanks, this looks promising. I merged this into the res-scale branch so I can check it out a bit more.

**Comment by Novum** [comment]
Tons and tons of validation spam with running this code.

**Comment by vsonnier** [comment]
When loading a custom game save, like for Travail : https://www.quaddicted.com/reviews/travail.html
I got the following errors while loading a save:
```c
TextMgr_FreeTexture: not found
TextMgr_FreeTexture: not found
```
exactly 2 times, and my Quake logo menu graphic get corrupted, showing a random texture instead.

Command line: ` -particles 10000 -protocol 999 -game travail +map start`

Savegame: 
[s0.zip](https://github.com/Novum/vkQuake/files/5761326/s0.zip)

I think the problem lies with this commit, because reverting only `47aaa69effd96a6396906bb4b49ac15892379457 Restore r_scale option for resolution scaling`  from master seems to solve the issue.

Using latest VS 2019 x64 to compile.

Screenshot: 

Corrupted_Logo_cr

**Comment by vsonnier** [comment]
Sorry, I deleted my post, the problem I reported did not seem to be about r_scale, I'm opening a separate issue.

**Comment by Novum** [comment]
@rg3 I still plan on looking at this and merging it eventually. I just need to fix the validation stuff and double check everything. Thanks.

**Comment by rg3** [comment]
> @rg3 I still plan on looking at this and merging it eventually. I just need to fix the validation stuff and double check everything. Thanks.

No problem. I was building vkquake in release mode and I thought I hadn't introduced any validation problems, not realizing the -validation command line option needs _DEBUG. I have a fix for the errors I'm seeing here (Fedora 33), so I'll create a separate pull request.

**Pull request closed without merging**
