### PR TITLE
hand-picked minor mimalloc fixes/updates from mainstream

### PR DESCRIPTION
**Pull request by sezero**
mainstream commits:
https://github.com/microsoft/mimalloc/commit/a158aef235515116625e0ee27629d2b41d269142
https://github.com/microsoft/mimalloc/commit/e1b27a0fc24ab20d5ac80ba7f68d4cbc48b27a21
https://github.com/microsoft/mimalloc/commit/7bef5f5f5b2cde374e1ac8b38f708de88c2dee52
https://github.com/microsoft/mimalloc/commit/698bb2cae70dbe096d6ece60670ac5e3897f5da2
https://github.com/microsoft/mimalloc/commit/6e0f10dfd8e5ffe01f3f85dc30b562b4c703098a
https://github.com/microsoft/mimalloc/commit/c4663463d120adafa5ceae25b3c22e49d7fdf18f

### CODE REVIEW

**Comment by Novum** [comment]
Can we not just update the entire thing to latest?

**Comment by sezero** [comment]
> Can we not just update the entire thing to latest?

Of course. I had prepared this in case you wouldn't want new features of it.

Should I close?

**Comment by Novum** [comment]
Yeah I will just update the entire thing. Was planning on it anyway. Or just in case you already had a PR for that just merge it.

**Comment by sezero** [comment]
>  Or just in case you already had a PR for that just merge it.

Nope, I don't

**Comment by Novum** [comment]
Okay will do then.

**Comment by sezero** [comment]
We have our local patches applied for mingw - I'll re-apply them when you upgrade (unless you do.)

**Pull request closed without merging**
