### PR TITLE
sync with quakespasm svn repository up to r1364

### PR DESCRIPTION
**Pull request by sezero**
(hopefully nothing missing.)

### CODE REVIEW

**Comment by mdeguzis** [comment]
I think the latest release noted future commits/releases will be bug fix only. I assume then Quakspasm still is active.

**Comment by sezero** [comment]
Hm, had not read the last vkquake release notes.. Well, this is mostly
a merge of minor maintenance work and 3rd-party lib updates from qs,
and you guys are free to accept or reject it.

**Comment by mdeguzis** [comment]
I just help out with the Linux legwork. You'll have to see what Novum thinks.

**Comment by Novum** [comment]
Updating to latest QuakeSpasm is fine and I will probably continue doing that in the future. I will take a look at the pull request later.

**Pull request merged**
