### PR TITLE
remove some C99'isms (for loop initial declarations)

### PR DESCRIPTION
**Pull request by sezero**
so that it builds with some older compilers.
tested build with mingw (gcc-3.4.5) and mingw-w64 (gcc-4.5.4).

### CODE REVIEW

**Comment by mdeguzis** [comment]
I sure hope this doesn't break the Linux builds. This was removed then readded back. If I must, I will `+=` the flag in my package rules. See: 14fa407

**Comment by sezero** [comment]
@mdeguzis: The intention is to be able to build w/o needing and extra -std flag,
ad the changeset can't ever possibly break linux builds.

**Comment by mdeguzis** [comment]
Yes, I understand, as my edit noted, I misread your changes. Sorry.

**Comment by Novum** [comment]
I appreciate the fixes for this. I just can't get my head to not do this when I write code :)

**Comment by Novum** [comment]
Although I wonder what systems have Vulkan support and don't support C99?

**Comment by sezero** [comment]
> Although I wonder what systems have Vulkan drivers but not a C99 compiler?

Probably not much.  However a cross-build environment might not have the newest
and greatest of compilers but still can produce a target binary just fine (such as the
mingw32 one I had tested.)

**Pull request merged**
